### ISSUE TITLE
'sdProcessChar' was not declared in this scope

### ISSUE THREAD

**Issue by davidvumbaco** [DavidMCarek/WEEGI#2]
I got this error when trying to verify the sketch in Arduino 1.8.4 before flashing.

exit status 255
'sdProcessChar' was not declared in this scope

Best I can tell we need a forward declaration of sdProcessChar, but I am not familiar with programming in C or arduino.

Any help would be appreciated.

DV
<img width="1009" alt="screen shot 2017-12-19 at 2 12 11 pm" src="https://user-images.githubusercontent.com/29783221/34176727-a2e89716-e4c6-11e7-91f5-c14bd6aeba8f.png">

**Comment by davidvumbaco** [comment]
I fixed my issue. Their needed to be the standard "SD_Card_Stuff" tab also in the sketch along side the updated cyton firmware tab. This contained the definitions/declarations for the missing variables.

**Comment by kevinlrak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create backend DB connection](https://trello.com/c/6Un9Xgb0/2-create-backend-db-connection)
